drop table keyspace1.user;
drop table keyspace1.event;
drop table keyspace1.options;
drop table keyspace1.clothers;
drop table keyspace1.user_event;
drop table keyspace1.event_clothers;
drop table keyspace1.clothers_options;
drop table keyspace1.user_clothers_options;

DROP TYPE keyspace1.user_name_type;
DROP TYPE keyspace1.parametr_type;
DROP TYPE keyspace1.event_type; 


drop keyspace keyspace1;

